# Generated x86-64 assembly (AT&T syntax)
# Target: System V AMD64 ABI
# Platform: macOS/Linux compatible
# Generated by C Compiler - Code Generation Phase
# Supports external library integration (printf, malloc, etc.)

# macOS Mach-O format

# Text section for executable code
.text


    # Function: main
.globl main
main:
    # Function prologue - System V AMD64 ABI


main_entry:
    # t0_0 = 42
    # x_0 = t0_0
    # Return x_0
    # Function epilogue - System V AMD64 ABI
    pushq %rbp
    movq %rsp, %rbp
    movq $42, %r11
    movq %r11, %r10
    movq %r10, %rax
    movq %rbp, %rsp
    popq %rbp
    ret

# End of generated assembly
