# Generated x86-64 assembly (AT&T syntax)
# Target: System V AMD64 ABI
# Platform: macOS/Linux compatible
# Generated by C Compiler - Code Generation Phase
# Supports external library integration (printf, malloc, etc.)
# Debug symbols enabled for gdb/lldb debugging

# macOS Mach-O format

.file 1 "calculator.c"
# Text section for executable code
.text


    # Function: calculate
    .type calculate, @function
.globl calculate
calculate:
    # Function prologue - System V AMD64 ABI
    .cfi_startproc
    pushq %rbp
    .cfi_def_cfa_offset 16
    .cfi_offset %rbp, -16
    movq %rsp, %rbp
    .cfi_def_cfa_register %rbp

    # result_0 = x_0 res y_0
    movq <SPILLED>, %r11
    addq <SPILLED>, %r11
    # Return result_0
    movq <SPILLED>, %rax
    # Function epilogue - System V AMD64 ABI
    movq %rbp, %rsp
    popq %rbp
    ret
    .cfi_endproc

# End of generated assembly
